import { LayoutProvider } from "@/context/LayoutContext";
import "./globals.css";

export const metadata = {
  title: "P-2-P | Approver",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <LayoutProvider>
          {children}
        </LayoutProvider>
      </body>
    </html>
  );
}
